# print(type("Тут пишемо змінну, текст або число"))
name ,age ,city ,clas ,pet,predmet,craina,xobu,pyt,eda = "Ярослав", 11.1 , "Київ" , 5 ,"Собака" , "Математика","Україне","Футбол","Испание","Шашлик"
print ("Привіт! Мене звати",name)
print ("Мені",age,"років" )
print ("Я живу в ",craina)
print ("Я живу в городе",city)
print ("Я учусь в",clas,"класі")
print ("Мое улюблене животние",pet)
print ("Мой любий придмет",predmet)
print ("Мое хоби",xobu)
print ("Я хочу побивать в",pyt)
print ("Mоя любимая еда",eda)
print (type(city))
print (type(age))
print (type(clas))